# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "environment-states"
    key                  = "vs-enterprise/staging/global/resource_groups/terraform.tfstate"
    resource_group_name  = "rg-terragrunt-example-001"
    storage_account_name = "stterragruntexample003"
    subscription_id      = "3bfeb287-1a11-406b-8e99-0db004b08e8c"
  }
}
