name: 'Terraform Github Actions'
default:
  run:
    working-directory:"Terraform"
  on:
    - push
  jobs:
    terraform:
      name: 'Terraform'
      runs-on: ubuntu-latest
    
    steps:
      - uses: action/checkout@master
      - name: 'Terraform Init'
        id: init
        run: terraform init
        env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    
    
  