
 name: 'Terraform GitHub Actions'
 defaults:
   run:
     working-directory: "./"
 on:
   - pull_request
   - push
 jobs:
   terraform:
     name: 'Terraform'
     runs-on: ubuntu-latest

     env:
      TF_VAR_client_id: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_client_secret: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_subscription_id: ${{ secrets.GITHUB_TOKEN }}
      TF_VAR_tenant_id: ${{ secrets.GITHUB_TOKEN }}


     steps:
       - uses: actions/checkout@master
       - name: 'Terraform Init'
         id: init
         run: terraform init
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Terraform Validate
         id: validate
         run: terraform validate
       - name: Terraform Apply
         id: apply
         run: terraform Apply